name: .NET

on:
  push:
    branches: [ nightly, master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Pack
      run: dotnet pack --include-source --no-build --no-restore --configuration Release

    - name: Publish BotFramework
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: BotFramework/BotFramework.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
                
    - name: Publish Abstractions
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: BotFramework.Abstractions/BotFramework.Abstractions.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
        
    - name: Publish Hosting
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: BotFramework.Hosting/BotFramework.Hosting.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true

    - name: Publish Identity
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: BotFramework.Identity/BotFramework.Identity.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
